### ISSUE TITLE
Where I have to Place API Key

### ISSUE THREAD

**Issue by Sreenivas7463** [RobertBrunhage/open-weather-app#9]
Where I have to Place API Key

**Comment by RobertBrunhage** [comment]
You create a .env file in the root directory of the project then add the following:

OPEN_WEATHER_API_KEY = MyAPIKeyWouldBeHere

Let me know if it works :)

**Comment by Sreenivas7463** [comment]
Hi  Robert Brunhage,
I Created .env file with my api key but it is not working for me

**Comment by RobertBrunhage** [comment]
1. Be on Flutter channel beta so you can take part of flutter web.
https://flutter.dev/docs/get-started/web

2. See if you have chrome as a device by typing `flutter devices`. Chrome should be listed here

3. Now you create the .env file in the root directory of the project and paste as my previous comment.

4. type `flutter run -d chrome` to run in the chrome browser.

These should be all the steps, just verified it. If one of the steps are unclear please let me know :)

**Comment by RobertBrunhage** [comment]
I am closing this issue, if you are still having the same problem, let me know and I will reopen it again :)
